#This program gets all the names and variables that we will need, it writes them to a file called "botVars.txt"
print("make sure to enter these values in quotation marks")
botName = input("please enter your bot's twitter username ex: my_ebooks: ")
APIKey = input("please enter your API key (I would copy and paste: )")
APISecret = input("please enter your API secret: ")
AccessToken = input("please enter your Access Token: ")
AccessTokenSecret = input("please enter your Access Token Secret: ")
file = open("botVars.txt", "w")
file.write(str(botName))
file.write("\n")
file.write(str(APIKey))
file.write("\n")
file.write(str(APISecret))
file.write("\n")
file.write(str(AccessToken))
file.write("\n")
file.write(str(AccessTokenSecret))
file.write("\n")
file.close()
